### ISSUE TITLE
Error in uniroot  no sign change found in 1000 iterations

### ISSUE THREAD

**Issue by EDF82** [lfmcmillan/geneplot#2]
Hi,
I have recently been trying out geneplot for some fisheries stock identification projects I am working on and have found it very useful. I have started getting the following error when I run the script. 

My error:   Error in uniroot(f, c(lower, upper), f.lower = f.lower, f.upper = f.upper, : no sign change found in 1000 iterations 

I still get an output of results and also a figure but I wanted to check if you have seen this error and if you know what it means.

Thanks for your help

**Comment by lfmcmillan** [comment]
Hi, this error is one that commonly occurs when the saddlepoint approximation fails at the outer edges of the population's genetic distribution. The error appears to the user, but the output is caught by the code so that it does not stop the completion of the calculation, and it only leads to very small differences in the approximation result. Version 0.2.0 onwards does not use uniroot and so no longer produces this error.
